### PR TITLE
Containerized Gazee

### PR DESCRIPTION
**Pull request by MayankTahil**
Updated Readme.md with instructions on how to build docker image and run docker container for gazee. Dockerfile created starts from a light weight =python:3.6.2-alpine base image (~30 MB). It installs all dependencies and required python packages.

Notes:

Gazee service works within the container successfully and I can logon to the WebUI.
Run the container with volume mounts to /data (for comic library), /certs (for certificates), and /mylar (for MylarDB).
Recommendations:

You may want to build the image and push to your docker hub account if you'd like and update the readme accordingly. Replace all instances of mayankt in the text with your username.
Observations:

When there is a volume mount from local directory to the container directory /data where the local host directory only contains a .cbr file, container/code crashes ungracefully when configured path for library is set to /data in the UI.

We may want a step in the Dockerfile or python code logic to set the default library path to /data unless specified. Otherwise user is manually setting the library directory to /data when deployed as a container.

### CODE REVIEW

**Comment by hubbcaps** [comment]
The reason the code fails is due to one of the main directories Gazee works out of is data under the Gazee install directory. Having anything operate out of a dir named data is a bad idea, especially the library directory.

I'd instead propose four working directories:

- comics
For obvious reasons

- certs
I actually didn't think about this one, good call.

- gazee
App logs are placed under data in the install directory, so having this exposed will allow easy access to those, and also the app.ini if wanted.

- mylar
To actually mount the Myalr.db is available.

I was actually just about to upload my own version of this, but yours is much cleaner so far and I'd like to see it once setup against proper directory structures.

**Comment by MayankTahil** [comment]
Feel free to update the Dockerfile if you'd like :) or you can have me take another swing at it. I won't be able to get back to my computer to work on this until Sunday evening so up to ya! Just let me know with your reply if you'd like me to finish what I started come Sunday.

**Comment by hubbcaps** [comment]
I'll go ahead and merge this into development for now and make the necessary changes to get it to not choke on data, and then push it up to master and dockerhub.

Thank you very much for the contribution, the first one in hopefully a long line to making Gazee the best damn web reader out there.

Cheers Friend, enjoy the rest of your weekend!

**Comment by hubbcaps** [comment]
Just to keep you updated, I've gone ahead and broken the docker file out into a separate repository.

https://github.com/hubbcaps/docker-gazee

I've tied it in with this dockerhub repo

https://hub.docker.com/r/hubcapps/docker-gazee/

I decided to break it out due to needing some certain settings that had to be maintained and changed within gazee itself, and I've ended up modling it after the linuxserver.io style of docker containers.

**Pull request merged**
